# Quickstart for GitHub Actions
# https://docs.github.com/en/actions/quickstart

name: Strong CI
on: [ push, pull_request, workflow_dispatch ]
jobs:
  test:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Strong CI by multiply java versions

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Cache local Maven repository
        uses: actions/cache@v4
        # https://github.com/actions/cache/blob/main/examples.md#java---maven
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # image(ubuntu-latest/ubuntu-24.04) included Java 8/11/17/21/25
      #   https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#java
      - name: Run integration test
        run: scripts/integration-test.sh

      - name: Remove self maven install files
        run: rm -rf $HOME/.m2/repository/com/alibaba/{transmittable-thread-local,ttl}*

      # https://github.com/codecov/codecov-action
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # https://remarkablemark.org/blog/2017/10/12/check-git-dirty/
      - name: Check git dirty
        run: |
          git status --short
          [ -z "$(git status --short)" ]
